### PR TITLE
Fix issue rendering hosts with unexpected CPU brand string

### LINKED ISSUE #1604: All Host page (and others) not rendering hosts
Initially, when first using the app, the UI will load hosts properly when they're visiting the All Hosts pages or any label (online, darwin, etc. At some instant however, the app will stop showing hosts in the UI. From this point forward, no hosts are able to be shown in the UI as cards or in the list. The sidebar, however, stays correct. Consider the following screenshot. The sidebar indicates that 11 hosts are online, but they are not rendered on the page:

image

@groob has debugged this a bit and determined that the response from the server contains the correct host data and has speculated that a new version of a JS dependency may be causing the rendering bug.

No noticeable errors occur in the console when this occurs and there is not currently a reliable set of reproduction steps.

### PR DESCRIPTION
**Pull request by zwass**
- Hosts with unexpected CPU brand string render properly
- Other unexpected host CPU information renders properly
- Add tests for host CPU parsing

Fixes #1604

### CODE REVIEW

File: frontend/redux/nodes/entities/hosts/helpers.js [hunk 1]
```diff
@@ -4,14 +4,20 @@ export const parseEntityFunc = (host) => {
...
 
-  let clockSpeed = null;
-  let clockSpeedFlt = null;
   let hostCpuOutput = null;
-
-  if (host && host.cpu_brand) {
-    clockSpeed = host.cpu_brand.split('@ ')[1] || host.cpu_brand.split('@')[1];
-    clockSpeedFlt = parseFloat(clockSpeed.split('GHz')[0].trim());
-    hostCpuOutput = `${host.cpu_physical_cores} x ${Math.floor(clockSpeedFlt * 10) / 10} GHz`;
+  if (host) {
```
Comment (groob) [inline frontend/redux/nodes/entities/hosts/helpers.js:8]: Would it be possible to just do away with the parsed variant, and to print the string as is?

If not, the current implementation LGTM

File: frontend/redux/nodes/entities/hosts/helpers.js [hunk 2]
```diff
@@ -4,14 +4,20 @@ export const parseEntityFunc = (host) => {
...
+    let clockSpeedOutput = null;
+    try {
+      const clockSpeed = host.cpu_brand.split('@ ')[1] || host.cpu_brand.split('@')[1];
+      const clockSpeedFlt = parseFloat(clockSpeed.split('GHz')[0].trim());
+      clockSpeedOutput = Math.floor(clockSpeedFlt * 10) / 10;
+    } catch (e) {
+      // Some CPU brand strings do not fit this format and we can't parse the
```
Comment (groob) [inline frontend/redux/nodes/entities/hosts/helpers.js:15]: Should there be a console.log(e) here?

File: frontend/redux/nodes/entities/hosts/helpers.js (hunk 1 above)
Comment (zwass) [reply frontend/redux/nodes/entities/hosts/helpers.js:8]: Not with the current design
screen shot 2017-11-13 at 7 35 44 pm

File: frontend/redux/nodes/entities/hosts/helpers.js (hunk 2 above)
Comment (zwass) [reply frontend/redux/nodes/entities/hosts/helpers.js:15]: I had debated adding a console log, but thought it may end up fairly noisy. We probably should add it and 99% of users won't notice the noise.

Comment (zwass) [reply frontend/redux/nodes/entities/hosts/helpers.js:15]: This is done.

**Comment by groob** [comment]
@zwass want to add this to CHANGELOG too?
